"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useRef, useState, type FormEvent } from "react";
import { CheckCircle2, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { useAuth } from "@/features/auth/auth-provider";
import { API_URL, DEMO_MODE, getOwnProfile, updateProfileResource } from "@/lib/api";
import { assetIdFromUrl, downloadAsset, extensionApi, uploadAsset, type HrOptions, type HrRequest } from "@/features/profile-extensions/api";
import { ExtensionError } from "@/features/profile-extensions/profile-extensions-panel";
const labels = { PENDING: "Đang chờ duyệt", APPROVED: "Đã duyệt", REJECTED: "Từ chối" };
const selectClass = "h-12 w-full rounded-xl border border-border bg-surface px-3 text-sm";
function RequestCard({ request, reviewing = false }: {
    request: HrRequest;
    reviewing?: boolean;
}) {
    const { session } = useAuth();
    const cache = useQueryClient();
    const [points, setPoints] = useState("0");
    const [note, setNote] = useState("");
    const [downloadError, setDownloadError] = useState<unknown>(null);
    const review = useMutation({ mutationFn: (status: "APPROVED" | "REJECTED") => extensionApi(session!, `/competency-requests/${request.id}/review`, "POST", { status, pointsAwarded: status === "APPROVED" ? Number(points) : 0, reviewNote: note || null }), onSuccess: async () => { await cache.invalidateQueries({ queryKey: ["hr-requests"] }); await cache.invalidateQueries({ queryKey: ["profile-extensions"] }); } });
    const evidence = request.sourceSnapshot.credentialUrl || request.sourceSnapshot.evidenceUrl;
    const assetId = evidence ? assetIdFromUrl(evidence) : undefined;
    const safeExternal = evidence && /^https?:\/\//i.test(evidence);
    return <Card><CardContent className="space-y-4 p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-primary">{request.sourceType === "CERTIFICATION" ? "Chứng chỉ" : "Giải thưởng"}</p><h3 className="mt-1 text-lg font-bold">{request.sourceSnapshot.name || "Nội dung đã gửi"}</h3><p className="mt-1 text-sm text-muted">{request.sender?.name ? `${request.sender.name} · ` : ""}{new Date(request.createdAt).toLocaleString("vi-VN")}</p></div><Badge tone={request.status === "APPROVED" ? "success" : "neutral"}>{labels[request.status]}</Badge></div><dl className="grid gap-2 text-sm md:grid-cols-2">{Object.entries({ "Đơn vị cấp / trao": request.sourceSnapshot.issuer, "Điểm / xếp loại": request.sourceSnapshot.score, "Ngày cấp / trao": request.sourceSnapshot.issuedAt || request.sourceSnapshot.awardedAt, "Mô tả": request.sourceSnapshot.description }).filter(([, value]) => value).map(([label, value]) => <div key={label}><dt className="text-muted">{label}</dt><dd className="mt-1 whitespace-pre-wrap">{value}</dd></div>)}</dl><p className="text-xs text-muted">Đây là bản chụp nội dung tại thời điểm gửi, không đổi khi hồ sơ gốc được sửa hoặc xóa.</p>{request.message ? <p className="rounded-xl bg-background p-3 text-sm">Lời nhắn: {request.message}</p> : null}{assetId ? <Button variant="secondary" onClick={() => void downloadAsset(session!, assetId, request.sourceSnapshot.name || "minh-chung").catch(setDownloadError)}>Tải minh chứng riêng tư</Button> : safeExternal ? <a className="text-sm font-semibold text-primary underline" target="_blank" rel="noopener noreferrer" href={evidence!}>Mở minh chứng</a> : null}{request.reviewedAt ? <p className="text-sm">{labels[request.status]} · {request.pointsAwarded} điểm · {request.reviewNote || "Không có ghi chú"}</p> : null}<ExtensionError error={review.error || downloadError}/>{reviewing && request.status === "PENDING" ? <div className="space-y-3 border-t border-border pt-4"><label className="grid gap-2 text-sm font-semibold">Điểm đóng góp (0–100)<Input type="number" min={0} max={100} step={1} value={points} onChange={(event) => setPoints(event.target.value)} disabled={review.isPending}/></label><label className="grid gap-2 text-sm font-semibold">Ghi chú phản hồi<textarea className="min-h-24 rounded-xl border border-border p-3 text-sm" value={note} onChange={(event) => setNote(event.target.value)} disabled={review.isPending}/></label><p className="text-xs text-muted">Quyết định được lưu một lần. Từ chối không cộng điểm.</p><div className="flex flex-wrap gap-2"><Button disabled={review.isPending || !Number.isInteger(Number(points)) || Number(points) < 0 || Number(points) > 100} onClick={() => review.mutate("APPROVED")}><CheckCircle2 size={16} aria-hidden="true"/>Duyệt yêu cầu</Button><Button variant="secondary" disabled={review.isPending} onClick={() => review.mutate("REJECTED")}>Từ chối</Button></div></div> : null}</CardContent></Card>;
}
export function CompetencyRequestsView() {
    const { session } = useAuth();
    const cache = useQueryClient();
    const [mode, setMode] = useState<"sent" | "received">("sent");
    const [filter, setFilter] = useState("");
    const [source, setSource] = useState("");
    const [employmentId, setEmploymentId] = useState("");
    const [recipientUserId, setRecipientUserId] = useState("");
    const [message, setMessage] = useState("");
    const [notice, setNotice] = useState("");
    const retry = useRef<{
        key: string;
        id: string;
    } | null>(null);
    const enabled = Boolean(session?.user.permissions.includes("profile:self")) && !DEMO_MODE;
    const options = useQuery({ queryKey: ["hr-options", session?.user.id], queryFn: () => extensionApi<HrOptions>(session!, "/competency-requests/options"), enabled });
    const profile = useQuery({ queryKey: ["core-profile", session?.user.id], queryFn: () => getOwnProfile(session!), enabled });
    const requests = useQuery({ queryKey: ["hr-requests", session?.user.id, mode, filter], queryFn: () => extensionApi<HrRequest[]>(session!, `/competency-requests/${mode}${mode === "received" && filter ? `?status=${filter}` : ""}`), enabled: enabled && (mode === "sent" || session?.user.role === "HR") });
    const send = useMutation({ mutationFn: () => { const [sourceType, sourceId] = source.split(":"); const body = { sourceType, sourceId, employmentId, recipientUserId, message: message || null }; const key = JSON.stringify(body); if (retry.current?.key !== key)
            retry.current = { key, id: crypto.randomUUID() }; return extensionApi(session!, "/competency-requests", "POST", { ...body, clientRequestId: retry.current.id }); }, onSuccess: async () => { setNotice("Đã gửi yêu cầu tới đúng HR bạn đã chọn."); retry.current = null; setSource(""); setMessage(""); await cache.invalidateQueries({ queryKey: ["hr-requests"] }); } });
    const attach = useMutation({ mutationFn: async (file: File) => { const [sourceType, sourceId] = source.split(":"); const asset = await uploadAsset(session!, file, "EVIDENCE"); const url = `${API_URL}${asset.downloadPath}`; await updateProfileResource(session!, sourceType === "CERTIFICATION" ? "certifications" : "awards", sourceId, { profileVersion: profile.data!.profileVersion, ...(sourceType === "CERTIFICATION" ? { credentialUrl: url } : { evidenceUrl: url }) }); }, onSuccess: async () => { setNotice("Đã gắn tệp vào nội dung hồ sơ. Bấm gửi để HR nhận bản chụp mới."); await cache.invalidateQueries({ queryKey: ["core-profile"] }); await cache.invalidateQueries({ queryKey: ["profile-assets"] }); } });
    function submit(event: FormEvent) { event.preventDefault(); setNotice(""); send.mutate(); }
    if (DEMO_MODE)
        return <Card><CardContent className="p-6">Duyệt HR cần bản QC kết nối FastAPI. Chế độ mẫu không gửi yêu cầu thật.</CardContent></Card>;
    if (!enabled)
        return <Card><CardContent className="p-6">Tài khoản này không có hồ sơ cá nhân để gửi yêu cầu năng lực.</CardContent></Card>;
    const companyId = options.data?.employments.find((item) => item.id === employmentId)?.companyId;
    const recipients = options.data?.recipients.filter((item) => item.companyId === companyId) || [];
    return <div className="space-y-6"><header><p className="text-sm font-semibold text-primary">Hồ sơ · Xác nhận năng lực</p><h1 className="mt-2 text-3xl font-bold">Yêu cầu chứng chỉ & giải thưởng</h1><p className="mt-2 text-muted">Chọn công ty đang làm việc và một HR cụ thể. Chỉ người nhận đó được duyệt.</p></header>{session?.user.role === "HR" ? <div className="flex gap-2" role="group" aria-label="Hộp thư yêu cầu"><Button variant={mode === "sent" ? "primary" : "secondary"} aria-pressed={mode === "sent"} onClick={() => setMode("sent")}>Đã gửi</Button><Button variant={mode === "received" ? "primary" : "secondary"} aria-pressed={mode === "received"} onClick={() => setMode("received")}>Gửi đến tôi</Button></div> : null}{mode === "sent" ? <Card><CardHeader><h2 className="text-lg font-bold">Gửi xác nhận mới</h2></CardHeader><CardContent><form onSubmit={submit} className="space-y-4"><ExtensionError error={options.error || profile.error || send.error || attach.error}/><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Chứng chỉ hoặc giải thưởng<select required className={selectClass} value={source} onChange={(e) => setSource(e.target.value)}><option value="">Chọn nội dung trong hồ sơ</option>{profile.data?.certifications.map((item) => <option key={item.id} value={`CERTIFICATION:${item.id}`}>Chứng chỉ · {item.name}</option>)}{profile.data?.awards.map((item) => <option key={item.id} value={`AWARD:${item.id}`}>Giải thưởng · {item.name}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Kỳ làm việc hiện tại<select required className={selectClass} value={employmentId} onChange={(e) => { setEmploymentId(e.target.value); setRecipientUserId(""); }}><option value="">Chọn công ty / kỳ làm việc</option>{options.data?.employments.map((item) => <option key={item.id} value={item.id}>{item.companyName} · {item.title}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">HR nhận yêu cầu<select required className={selectClass} value={recipientUserId} onChange={(e) => setRecipientUserId(e.target.value)} disabled={!employmentId}><option value="">Chọn người nhận cụ thể</option>{recipients.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Gắn / thay tệp minh chứng (không bắt buộc)<Input type="file" accept=".pdf,.png,.jpg,.jpeg,.gif,.webp,.doc,.docx,.xls,.xlsx" disabled={!source || attach.isPending || send.isPending} onChange={(e) => { const file = e.target.files?.[0]; if (file)
        attach.mutate(file); e.target.value = ""; }}/></label></div>{employmentId && !recipients.length ? <p role="status" className="text-sm text-muted">Công ty chưa có HR đang hoạt động. Liên hệ quản trị viên trước khi gửi.</p> : null}<label className="grid gap-2 text-sm font-semibold">Lời nhắn<textarea maxLength={4000} className="min-h-24 rounded-xl border border-border p-3 text-sm" value={message} onChange={(e) => setMessage(e.target.value)}/></label><Button disabled={send.isPending || attach.isPending || !source || !employmentId || !recipientUserId}><Send size={16} aria-hidden="true"/>{send.isPending ? "Đang gửi…" : "Gửi cho HR"}</Button>{notice ? <p role="status" className="text-sm text-primary">{notice}</p> : null}</form></CardContent></Card> : <label className="grid max-w-xs gap-2 text-sm font-semibold">Lọc trạng thái<select className={selectClass} value={filter} onChange={(e) => setFilter(e.target.value)}><option value="">Tất cả</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>}<section className="space-y-4"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-bold">{mode === "sent" ? "Yêu cầu đã gửi" : "Yêu cầu gửi đến tôi"}</h2><Button variant="secondary" onClick={() => void requests.refetch()}>Tải lại</Button></div><ExtensionError error={requests.error}/>{requests.isPending ? <p role="status">Đang tải yêu cầu…</p> : null}{requests.data?.length === 0 ? <p className="rounded-2xl border border-border bg-surface p-6 text-sm text-muted">Chưa có yêu cầu trong hộp thư này.</p> : null}{requests.data?.map((request) => <RequestCard key={request.id} request={request} reviewing={mode === "received"}/>)}</section></div>;
}
