"use client";
import { useQuery } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { useAuth } from "@/features/auth/auth-provider";
import { DEMO_MODE } from "@/lib/api";
import { extensionApi } from "./api";

type Insight = { profile: { id: string; name: string; jobTitle: string | null; contributionScore: number; attitudeScore: number | null; assessmentContributionScore: number | null; assessmentAttitudeScore: number | null }; skills: Array<{ id: string; skillId: string; name: string; category: string | null; level: number; note: string | null; sourceType: string }>; goalStatusCounts: Record<string, number>; activityCount: number; assessmentsReceivedCount: number };
const statusLabels: Record<string, string> = { NOT_STARTED: "Chưa bắt đầu", IN_PROGRESS: "Đang thực hiện", COMPLETED: "Hoàn thành", DONE: "Hoàn thành", CANCELLED: "Đã hủy", PAUSED: "Tạm dừng" };
export function SkillsInsightPanel({ userId }: { userId: string }) {
  const { session } = useAuth();
  const query = useQuery({ queryKey: ["skills-insight", session?.user.id, userId], queryFn: () => extensionApi<Insight>(session!, `/skills-competency/insight/${userId}`), enabled: Boolean(session?.user.permissions.includes("people:read")) && !DEMO_MODE });
  if (DEMO_MODE || !session?.user.permissions.includes("people:read")) return null;
  return <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Góc nhìn năng lực nhân sự</h2><p className="mt-1 text-sm text-muted">Tổng hợp dữ liệu đã lưu, không phải kết luận đánh giá từ AI.</p></div><Button variant="secondary" onClick={() => void query.refetch()} disabled={query.isFetching}>Tải lại</Button></div></CardHeader><CardContent className="space-y-5">{query.isPending ? <p role="status" className="text-sm text-muted">Đang tổng hợp năng lực…</p> : null}{query.error ? <p role="alert" className="text-sm text-danger">{query.error.message}</p> : null}{query.data ? <><dl className="grid grid-cols-2 gap-3 lg:grid-cols-5">{[["Điểm ghi nhận", query.data.profile.contributionScore], ["Đánh giá đóng góp", query.data.profile.assessmentContributionScore ?? "Chưa có"], ["Đánh giá thái độ", query.data.profile.assessmentAttitudeScore ?? "Chưa có"], ["Hoạt động", query.data.activityCount], ["Đánh giá nhận được", query.data.assessmentsReceivedCount]].map(([label, value]) => <div key={label} className="rounded-xl bg-background p-4"><dt className="text-sm text-muted">{label}</dt><dd className="mt-2 text-2xl font-bold">{value}</dd></div>)}</dl><div><h3 className="font-bold">Mục tiêu theo trạng thái</h3><div className="mt-3 flex flex-wrap gap-2">{Object.entries(query.data.goalStatusCounts).map(([status, count]) => <Badge key={status}>{statusLabels[status] || status}: {count}</Badge>)}{Object.keys(query.data.goalStatusCounts).length === 0 ? <p className="text-sm text-muted">Chưa có mục tiêu.</p> : null}</div></div><div><h3 className="font-bold">Kỹ năng và bối cảnh thực hành</h3><ul className="mt-3 grid gap-3 md:grid-cols-2">{query.data.skills.map((skill) => <li className="rounded-xl border border-border p-4" key={skill.id}><div className="flex justify-between gap-3"><p className="font-semibold">{skill.name}</p><span className="text-sm font-bold text-primary">{skill.level}/5</span></div><p className="mt-1 text-xs text-muted">{skill.category || "Chưa phân nhóm"} · {skill.sourceType === "SELF" ? "Tự đánh giá" : skill.sourceType === "IMPORT" ? "Từ tài liệu" : "Quản lý cập nhật"}</p>{skill.note ? <p className="mt-3 whitespace-pre-wrap text-sm">{skill.note}</p> : null}</li>)}</ul>{query.data.skills.length === 0 ? <p className="mt-3 text-sm text-muted">Chưa có kỹ năng.</p> : null}</div></> : null}</CardContent></Card>;
}
