"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { fieldClass, panelClass } from "@/features/career-ai/settings";
import type { Proposal } from "@/features/career-ai/api";

type TreeDraft = Omit<Proposal, "milestones"> & { milestones: Array<{ title: string; description?: string | null; dueDate?: string | null; tasks: Array<{ title: string; metric?: string | null; done?: boolean }> }> };
export function RoadmapTreeEditor({ initial, pending, onSave, onCancel, saveLabel = "Lưu chỉnh sửa lộ trình", allowCompletion = true }: { initial: TreeDraft; pending: boolean; onSave: (draft: TreeDraft) => void; onCancel: () => void; saveLabel?: string; allowCompletion?: boolean }) {
  const [draft, setDraft] = useState(initial);
  const [confirmCancel, setConfirmCancel] = useState(false);
  function patchMilestone(index: number, update: Partial<TreeDraft["milestones"][number]>) { setDraft((value) => ({ ...value, milestones: value.milestones.map((step, at) => at === index ? { ...step, ...update } : step) })); }
  const valid = draft.title.trim() && draft.milestones.every((step) => step.title.trim() && step.tasks.every((task) => task.title.trim()));
  return <form className={panelClass} onSubmit={(event) => { event.preventDefault(); if (valid) onSave(draft); }}><fieldset disabled={pending} className="space-y-5"><legend className="text-xl font-bold">Xem và chỉnh sửa lộ trình</legend><p className="text-sm text-muted">Chỉ lưu khi bạn xác nhận. Thêm, sửa, xóa và sắp xếp chặng/công việc bên dưới.</p><label className="block text-sm font-semibold">Tên lộ trình<input required maxLength={180} className={fieldClass} value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Số tuần<input type="number" min={1} max={520} className={fieldClass} value={draft.durationWeeks ?? ""} onChange={(event) => setDraft({ ...draft, durationWeeks: event.target.value ? Number(event.target.value) : null })} /></label><label className="text-sm font-semibold">Giờ / tuần<input type="number" min={1} max={168} className={fieldClass} value={draft.hoursPerWeek ?? ""} onChange={(event) => setDraft({ ...draft, hoursPerWeek: event.target.value ? Number(event.target.value) : null })} /></label></div>
      {draft.milestones.map((step, index) => <section key={index} className="space-y-4 rounded-xl border border-border bg-background p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-bold">Chặng {index + 1}</h3><div className="flex flex-wrap gap-2">{([-1, 1] as const).map((direction) => <Button key={direction} type="button" variant="secondary" disabled={index + direction < 0 || index + direction >= draft.milestones.length} onClick={() => { const next = [...draft.milestones]; [next[index], next[index + direction]] = [next[index + direction], next[index]]; setDraft({ ...draft, milestones: next }); }}>{direction < 0 ? "Lên" : "Xuống"}</Button>)}<Button type="button" variant="ghost" disabled={draft.milestones.length === 1} onClick={() => setDraft({ ...draft, milestones: draft.milestones.filter((_, at) => at !== index) })}>Xóa chặng</Button></div></div><label className="block text-sm font-semibold">Tên chặng<input required maxLength={180} className={fieldClass} value={step.title} onChange={(event) => patchMilestone(index, { title: event.target.value })} /></label><label className="block text-sm font-semibold">Mô tả<textarea maxLength={2000} className={fieldClass} value={step.description ?? ""} onChange={(event) => patchMilestone(index, { description: event.target.value || null })} /></label><label className="block text-sm font-semibold">Hạn hoàn thành<input type="date" className={fieldClass} value={step.dueDate ?? ""} onChange={(event) => patchMilestone(index, { dueDate: event.target.value || null })} /></label>
        {step.tasks.map((task, at) => <div key={at} className="grid gap-3 rounded-xl border border-border bg-surface p-3 sm:grid-cols-2"><label className="text-sm font-semibold">Công việc {at + 1}<input required maxLength={180} className={fieldClass} value={task.title} onChange={(event) => patchMilestone(index, { tasks: step.tasks.map((item, number) => number === at ? { ...item, title: event.target.value } : item) })} /></label><label className="text-sm font-semibold">Tiêu chí đo lường<input maxLength={500} className={fieldClass} value={task.metric ?? ""} onChange={(event) => patchMilestone(index, { tasks: step.tasks.map((item, number) => number === at ? { ...item, metric: event.target.value || null } : item) })} /></label><label className={allowCompletion ? "flex min-h-11 items-center gap-2 text-sm" : "hidden"}><input type="checkbox" disabled={!allowCompletion} checked={task.done ?? false} onChange={(event) => patchMilestone(index, { tasks: step.tasks.map((item, number) => number === at ? { ...item, done: event.target.checked } : item) })} /> Đã hoàn thành</label><div className="flex flex-wrap gap-2">{([-1, 1] as const).map((direction) => <Button key={direction} type="button" variant="secondary" size="sm" disabled={at + direction < 0 || at + direction >= step.tasks.length} aria-label={`Đưa công việc ${at + 1} ${direction < 0 ? "lên" : "xuống"}`} onClick={() => { const next = [...step.tasks]; [next[at], next[at + direction]] = [next[at + direction], next[at]]; patchMilestone(index, { tasks: next }); }}>{direction < 0 ? "Lên" : "Xuống"}</Button>)}<Button type="button" variant="ghost" disabled={step.tasks.length === 1} onClick={() => patchMilestone(index, { tasks: step.tasks.filter((_, number) => number !== at) })}>Xóa công việc {at + 1}</Button></div></div>)}<Button type="button" variant="secondary" disabled={step.tasks.length >= 50} onClick={() => patchMilestone(index, { tasks: [...step.tasks, { title: "", metric: null, done: false }] })}>Thêm công việc</Button></section>)}
      <Button type="button" variant="secondary" disabled={draft.milestones.length >= 30} onClick={() => setDraft({ ...draft, milestones: [...draft.milestones, { title: "", description: null, dueDate: null, tasks: [{ title: "" }] }] })}>Thêm chặng</Button><div className="flex flex-wrap gap-2"><Button type="submit" disabled={!valid}>{pending ? "Đang lưu…" : saveLabel}</Button><Button type="button" variant="secondary" onClick={() => setConfirmCancel(true)}>Hủy</Button></div>{confirmCancel && <div role="alert"><p className="mb-2 text-sm">Bỏ thay đổi chưa lưu?</p><Button variant="danger" type="button" onClick={onCancel}>Bỏ thay đổi</Button> <Button variant="secondary" type="button" onClick={() => setConfirmCancel(false)}>Tiếp tục chỉnh sửa</Button></div>}</fieldset></form>;
}
