"use client";

import { useState } from "react";
import "./passport-print.css";
import { useQuery } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { apiRequest } from "@/lib/api";
import { Field, fieldClass, Loading, panelClass, Snapshot, statusLabel, Summary, TalentHeader, useTalentAction, useTalentQuery, useTalentScope } from "./shared";

function printSnapshot(id: string) {
  const source = document.getElementById(id);
  if (!source) return;
  const surface = document.createElement("div");
  surface.className = "passport-print-surface";
  surface.appendChild(source.cloneNode(true));
  document.body.appendChild(surface);
  try { window.print(); } finally { surface.remove(); }
}

type Passport = {person:{name:string;jobTitle:string|null};employments:Array<{id:string;title:string;startDate:string;endDate:string|null;status:string;version:number}>;assessments:Snapshot["assessments"];skills:Snapshot["skills"]};
type Share = {id:string;label:string;expiresAt:string;revokedAt:string|null;summaryId:string};
type Proposal={content:string;strengths:string[];growthAreas:string[]};

export function SnapshotView({snapshot,id}:{snapshot:Snapshot;id?:string}) {
  return <article id={id} className={`${panelClass} space-y-5 print:border-0 print:shadow-none`}><header><p className="text-xs font-semibold uppercase tracking-widest text-primary">Hộ chiếu nghề nghiệp đã xác nhận</p><h2 className="mt-3 text-2xl font-bold">{snapshot.name}</h2><p className="mt-2 text-muted">{snapshot.jobTitle}</p><p className="mt-2 text-xs text-muted">Ngày xác nhận: {new Date(snapshot.approvedAt).toLocaleDateString("vi-VN")}</p></header><p className="whitespace-pre-wrap text-sm leading-7">{snapshot.content}</p>{snapshot.evaluation&&<section><h3 className="mb-2 font-bold">Nhận định tổ chức</h3><p className="whitespace-pre-wrap text-sm leading-7">{snapshot.evaluation}</p></section>}<div className="grid gap-5 sm:grid-cols-2"><section><h3 className="font-bold">Điểm mạnh</h3><ul className="mt-2 list-inside list-disc space-y-2 text-sm">{snapshot.strengths.map((s,i)=><li key={i}>{s}</li>)}</ul></section><section><h3 className="font-bold">Hướng phát triển</h3><ul className="mt-2 list-inside list-disc space-y-2 text-sm">{snapshot.growthAreas.map((s,i)=><li key={i}>{s}</li>)}</ul></section></div><section><h3 className="mb-3 font-bold">Năng lực đã ghi nhận</h3><div className="flex flex-wrap gap-2">{snapshot.skills.map((s,i)=><span key={i} className="rounded-lg bg-background px-3 py-2 text-xs">{s.name} · {s.rating}/5 · Tự khai báo</span>)}</div></section>{Object.keys(snapshot.dimensionScores).length>0&&<section className="grid gap-3 sm:grid-cols-5">{Object.entries(snapshot.dimensionScores).map(([label,value])=><div className="rounded-xl bg-background p-3" key={label}><p className="text-xs text-muted">{({attendance:"Chuyên cần",proactiveness:"Chủ động",knowledge:"Kiến thức",skill:"Kỹ năng",activityParticipation:"Tham gia"} as Record<string,string>)[label]??label}</p><p className="mt-2 font-bold">{value}/10</p></div>)}</section>}<p className="text-xs text-muted">{snapshot.assessments.length} lượt đánh giá đã duyệt được đưa vào bản chụp này. Nội dung đã đóng băng tại thời điểm xác nhận.</p></article>;
}

export function TalentPassport() {
  const scopeState = useTalentScope();
  return <TalentPassportContent key={`${scopeState.session?.user.id}:${scopeState.companyId}`} scopeState={scopeState} />;
}

function TalentPassportContent({scopeState}: {scopeState: ReturnType<typeof useTalentScope>}) {
  const {session,ready,scope,selector,companyId} = scopeState;
  const primaryScope = session?.user.role === "SUPER_ADMIN" || session?.user.companyId === companyId;
  const self=ready&&primaryScope&&!!session?.user.permissions.includes("profile:self"); const canReview=ready&&primaryScope&&!!session?.user.permissions.includes("passport:approve");
  const [tab,setTab]=useState<"own"|"pending">("own"); const activeTab=self?tab:"pending";
  const summaryQuery=useTalentQuery<Summary[]>(`/career-passport/summaries?pending=${activeTab==="pending"}&${scope}`,ready&&(self||canReview));
  const profile=useTalentQuery<Passport>("/career-passport",self&&ready);
  const shares=useTalentQuery<Share[]>("/career-passport/shares",self&&ready);
  const action=useTalentAction(async()=>{await summaryQuery.refetch();if(self)await shares.refetch();});
  const [employmentId,setEmploymentId]=useState(""); const [content,setContent]=useState(""); const [strengths,setStrengths]=useState<string[]>([]); const [growthAreas,setGrowthAreas]=useState<string[]>([]); const [shareLink,setShareLink]=useState(""); const [shareDays,setShareDays]=useState(30); const [shareLabel,setShareLabel]=useState("");
  async function generate(){const result=await action.run<Proposal>("/career-passport/summaries/generate","POST",{employmentId:employmentId||null});if(result){setContent(result.content);setStrengths(result.strengths);setGrowthAreas(result.growthAreas);action.setMessage("Đã tạo đề xuất. Hãy xem và chỉnh sửa trước khi lưu.");}}
  async function save(){const result=await action.run("/career-passport/summaries","POST",{employmentId:employmentId||null,content,strengths:strengths.map(s=>s.trim()).filter(Boolean),growthAreas:growthAreas.map(s=>s.trim()).filter(Boolean)});if(result){setContent("");setStrengths([]);setGrowthAreas([]);action.setMessage("Đã lưu tổng kết để chờ xác nhận.");}}
  async function share(row:Summary){const result=await action.run<{token:string}>("/career-passport/shares","POST",{summaryId:row.id,label:shareLabel,expiresInDays:shareDays});if(result)setShareLink(`${window.location.origin}/passport/${result.token}`);}
  async function exportRow(row:Summary){const result=await action.run<Snapshot>(`/career-passport/summaries/${row.id}/export`,"GET");if(result){const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download="career-passport.json";link.click();URL.revokeObjectURL(url);}}
  return <main className="mx-auto max-w-6xl space-y-6"><TalentHeader title="Hộ chiếu nghề nghiệp" description="Tổng hợp trải nghiệm có căn cứ, xin xác nhận và chủ động chia sẻ bản đã duyệt. Liên kết công khai chỉ hiển thị bản chụp được xác nhận, không mở hồ sơ cá nhân đầy đủ."/>{selector}{ready&&!primaryScope&&<p role="status" className={`${panelClass} text-muted`}>Hộ chiếu và hàng chờ xác nhận chỉ khả dụng trong công ty chính của tài khoản. Membership bổ sung không cấp quyền xem hoặc duyệt hộ chiếu ở công ty khác.</p>}{action.feedback}<Loading loading={ready&&summaryQuery.isLoading} error={summaryQuery.error||profile.error||shares.error} retry={()=>summaryQuery.refetch()}/>
    <div className="flex gap-2">{self&&<Button variant={activeTab==="own"?"primary":"secondary"} onClick={()=>setTab("own")}>Tổng kết của tôi</Button>}{canReview&&<Button variant={activeTab==="pending"?"primary":"secondary"} onClick={()=>setTab("pending")}>Cần xác nhận</Button>}</div>
    {self&&activeTab==="own"&&profile.data&&<EmploymentEditor records={profile.data.employments} refresh={()=>profile.refetch()}/>}
    {self&&activeTab==="own"&&<section className={`${panelClass} space-y-4`}><h2 className="text-xl font-bold">Soạn tổng kết</h2><Field label="Giai đoạn làm việc"><select className={fieldClass} value={employmentId} onChange={e=>setEmploymentId(e.target.value)}><option value="">Toàn bộ quá trình</option>{profile.data?.employments.map(e=><option key={e.id} value={e.id}>{e.title} · {new Date(e.startDate).toLocaleDateString("vi-VN")}</option>)}</select></Field><div className="flex flex-wrap gap-3"><Button variant="secondary" disabled={action.busy} onClick={()=>void generate()}>AI đề xuất tổng kết</Button><Button variant="secondary" disabled={action.busy||!employmentId} onClick={()=>void action.run("/career-passport/summaries/request","POST",{employmentId})}>Yêu cầu tổng kết từ tổ chức</Button></div><Field label="Nội dung tổng kết"><textarea className={fieldClass} rows={7} value={content} onChange={e=>setContent(e.target.value)} placeholder="Viết tổng kết hoặc xem lại đề xuất của AI…"/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Điểm mạnh (mỗi dòng một mục)"><textarea className={fieldClass} rows={3} value={strengths.join("\n")} onChange={e=>setStrengths(e.target.value.split("\n"))}/></Field><Field label="Hướng phát triển (mỗi dòng một mục)"><textarea className={fieldClass} rows={3} value={growthAreas.join("\n")} onChange={e=>setGrowthAreas(e.target.value.split("\n"))}/></Field></div><Button disabled={action.busy||!content.trim()} onClick={()=>void save()}>Lưu tổng kết để xác nhận</Button></section>}
    {self&&activeTab==="own"&&<section className={`${panelClass} space-y-4`}><h2 className="font-bold">Tùy chọn chia sẻ bản đã duyệt</h2><div className="grid gap-3 sm:grid-cols-2"><Field label="Tên liên kết"><input className={fieldClass} value={shareLabel} onChange={e=>setShareLabel(e.target.value)} placeholder="Ví dụ: Hồ sơ gửi nhà tuyển dụng"/></Field><Field label="Hiệu lực (ngày)"><input className={fieldClass} type="number" min={1} max={365} value={shareDays} onChange={e=>setShareDays(Number(e.target.value))}/></Field></div>{shareLink&&<div className="space-y-2"><Field label="Liên kết vừa tạo — lưu lại trước khi rời trang"><input className={fieldClass} readOnly value={shareLink}/></Field><Button variant="secondary" onClick={()=>void navigator.clipboard.writeText(shareLink).then(()=>action.setMessage("Đã sao chép liên kết.")).catch(()=>action.setMessage("Hãy chọn và sao chép liên kết ở ô phía trên."))}>Sao chép liên kết</Button></div>}</section>}
    {summaryQuery.data?.map(row=><SummaryCard key={`${row.id}:${row.version}`} row={row} role={session?.user.role??""} userId={session?.user.id??""} canReview={canReview} refresh={()=>summaryQuery.refetch()} onShare={()=>share(row)} onExport={()=>exportRow(row)} busy={action.busy}/>)}
    {summaryQuery.data?.length===0&&<p className={panelClass}>Chưa có tổng kết trong mục này.</p>}
    {self&&activeTab==="own"&&<section className="space-y-3"><h2 className="text-lg font-bold">Liên kết đã tạo</h2>{shares.data?.map(s=><div className={`${panelClass} flex flex-wrap items-center justify-between gap-3`} key={s.id}><div><p className="font-semibold">{s.label||"Liên kết hộ chiếu"}</p><p className="text-sm text-muted">{s.revokedAt?"Đã thu hồi":`Hết hạn ${new Date(s.expiresAt).toLocaleDateString("vi-VN")}`}</p></div>{!s.revokedAt&&<Button variant="secondary" disabled={action.busy} onClick={()=>void action.run(`/career-passport/shares/${s.id}/revoke`,"PATCH")}>Thu hồi liên kết</Button>}</div>)}</section>}
  </main>;
}

function SummaryCard({row,role,userId,canReview,refresh,onShare,onExport,busy}:{row:Summary;role:string;userId:string;canReview:boolean;refresh:()=>unknown;onShare:()=>unknown;onExport:()=>unknown;busy:boolean}) {
  const [content,setContent]=useState(row.content);const action=useTalentAction(refresh);const own=row.ownerUserId===userId;
  const approve=canReview&&["BOD","COMPANY_ADMIN","SUPER_ADMIN"].includes(role)&&!own;
  const edit= row.source==="PERSONAL"?own:canReview&&["HR","COMPANY_ADMIN","SUPER_ADMIN"].includes(role)&&!!row.generatedAt;
  return <section className={`${panelClass} space-y-4`}><div className="flex flex-wrap justify-between gap-3"><h2 className="text-lg font-bold">{row.ownerName} · {row.source==="PERSONAL"?"Tổng kết cá nhân":"Tổng kết tổ chức"}</h2><span className="text-sm font-semibold text-primary">{statusLabel[row.status]}</span></div>{action.feedback}
    {row.status==="APPROVED"?<SnapshotView id={`passport-snapshot-${row.id}`} snapshot={row.snapshot}/>:<><Field label="Nội dung cần xác nhận"><textarea disabled={!edit||action.busy} className={fieldClass} rows={6} value={content} onChange={e=>setContent(e.target.value)}/></Field>{row.evaluation&&<div><h3 className="font-semibold">Nhận định đánh giá (khóa sau khi tạo)</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{row.evaluation}</p></div>}</>}
    <div className="flex flex-wrap gap-3">{row.status==="DRAFT"&&edit&&<Button variant="secondary" disabled={action.busy||content===row.content||!content.trim()} onClick={()=>void action.run(`/career-passport/summaries/${row.id}`,"PATCH",{expectedVersion:row.version,content})}>Lưu diễn giải</Button>}{row.status==="DRAFT"&&row.source==="ORGANIZATION_OFFBOARDING"&&!row.generatedAt&&approve&&<Button disabled={action.busy} onClick={()=>void action.run(`/career-passport/summaries/${row.id}/trigger`,"POST",{expectedVersion:row.version})}>AI tạo tổng kết tổ chức</Button>}{row.status==="DRAFT"&&approve&&row.content&&<Button disabled={action.busy} onClick={()=>void action.run(`/career-passport/summaries/${row.id}/approve`,"POST",{expectedVersion:row.version})}>Xác nhận & đóng băng nội dung</Button>}{row.status==="APPROVED"&&own&&<><Button disabled={busy} onClick={()=>void onShare()}>Tạo liên kết chia sẻ</Button><Button variant="secondary" disabled={busy} onClick={()=>void onExport()}>Tải bản JSON</Button><Button variant="ghost" onClick={()=>printSnapshot(`passport-snapshot-${row.id}`)}>In / lưu PDF</Button></>}</div>
  </section>;
}

function EmploymentEditor({records,refresh}:{records:Passport["employments"];refresh:()=>unknown}) {
  const [editing,setEditing]=useState<Passport["employments"][number]|null>(null);const [visible,setVisible]=useState(false);const [title,setTitle]=useState("");const [start,setStart]=useState("");const [end,setEnd]=useState("");const action=useTalentAction(refresh);
  function open(row:Passport["employments"][number]|null){setEditing(row);setTitle(row?.title??"");setStart(row?.startDate.slice(0,10)??"");setEnd(row?.endDate?.slice(0,10)??"");setVisible(true);}
  return <section className={`${panelClass} space-y-4`}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-bold">Quá trình làm việc</h2><Button variant="secondary" onClick={()=>open(null)}>Thêm giai đoạn</Button></div>{action.feedback}{records.map(row=><div key={row.id} className="flex flex-wrap items-center justify-between gap-3 border-t border-border pt-3"><div><p className="font-semibold">{row.title}</p><p className="text-xs text-muted">{new Date(row.startDate).toLocaleDateString("vi-VN")} — {row.endDate?new Date(row.endDate).toLocaleDateString("vi-VN"):"Hiện tại"}</p></div><Button size="sm" variant="ghost" onClick={()=>open(row)}>Chỉnh sửa</Button></div>)}{visible&&<form className="space-y-4 rounded-xl bg-background p-4" onSubmit={async e=>{e.preventDefault();const result=await action.run(editing?`/career-passport/employments/${editing.id}`:"/career-passport/employments",editing?"PATCH":"POST",{title,startDate:start,endDate:end||null,...(editing?{expectedVersion:editing.version}:{})});if(result)setVisible(false);}}><Field label="Chức danh"><input required className={fieldClass} value={title} onChange={e=>setTitle(e.target.value)}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Ngày bắt đầu"><input required type="date" className={fieldClass} value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Ngày kết thúc (để trống nếu đang làm)"><input type="date" min={start} className={fieldClass} value={end} onChange={e=>setEnd(e.target.value)}/></Field></div><div className="flex gap-3"><Button disabled={action.busy}>Lưu giai đoạn</Button><Button type="button" variant="secondary" onClick={()=>setVisible(false)}>Hủy</Button></div></form>}</section>;
}

export function TalentPublicPassport({token}:{token:string}) {
  const query=useQuery<Snapshot>({queryKey:["public-passport",token],queryFn:()=>apiRequest<Snapshot>(`/passport/${encodeURIComponent(token)}`,{cache:"no-store"}),retry:false});
  return <main className="mx-auto min-h-screen max-w-4xl space-y-5 bg-background px-4 py-10"><Loading loading={query.isLoading} error={query.error} retry={()=>query.refetch()}/>{query.data&&<><SnapshotView id="passport-public-snapshot" snapshot={query.data}/><Button className="print:hidden" variant="secondary" onClick={()=>printSnapshot("passport-public-snapshot")}>In / lưu PDF</Button></>}</main>;
}
