"use client";

import {useState} from "react";
import Link from "next/link";
import * as Dialog from "@radix-ui/react-dialog";
import {Button} from "@/components/ui/button";
import {Field,fieldClass,Loading,panelClass,TalentHeader,useTalentAction,useTalentQuery,useTalentScope} from "./shared";

type Requirement={id:string;companyId:string;title:string;description:string;requiredSkills:string[];status:"open"|"closed";version:number};
type Matches={summary:string;matches:Array<{userId:string;name:string;jobTitle:string|null;matchScore:number;rationale:string}>};
export function TalentRequirements(){
  const {session,ready,scope,companyId,selector}=useTalentScope();
  const allowed=!!session?.user.permissions.includes("people:read");const manage=!!session?.user.permissions.includes("people:write");
  const rows=useTalentQuery<Requirement[]>(`/job-requirements?${scope}`,ready&&allowed);const action=useTalentAction(()=>rows.refetch());
  const [editing,setEditing]=useState<Requirement|null>(null);const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [skills,setSkills]=useState("");const [status,setStatus]=useState("open");const [removing,setRemoving]=useState<Requirement|null>(null);const [matches,setMatches]=useState<Record<string,Matches>>({});
  function clear(){setEditing(null);setTitle("");setDescription("");setSkills("");setStatus("open");}
  function edit(row:Requirement){setEditing(row);setTitle(row.title);setDescription(row.description);setSkills(row.requiredSkills.join(", "));setStatus(row.status);document.getElementById("requirement-title")?.focus();}
  return <main className="mx-auto max-w-6xl space-y-6"><TalentHeader title="Nhu cầu nhân sự" description="Ghi rõ nhu cầu và kỹ năng cần thiết, sau đó đối chiếu với năng lực nhân sự trong doanh nghiệp. AI trả về phân tích để bạn cân nhắc; không tự động thay đổi phân công."/>{selector}{!allowed&&<p>Bạn chưa được cấp quyền xem nhu cầu nhân sự.</p>}{action.feedback}<Loading loading={ready&&allowed&&rows.isLoading} error={rows.error} retry={()=>rows.refetch()}/>
    {manage&&ready&&<form className={`${panelClass} space-y-4`} onSubmit={async e=>{e.preventDefault();const body={companyId,title,description,requiredSkills:skills.split(",").map(s=>s.trim()).filter(Boolean),...(editing?{expectedVersion:editing.version,status}:{})};const result=await action.run(editing?`/job-requirements/${editing.id}`:"/job-requirements",editing?"PATCH":"POST",body);if(result){clear();action.setMessage("Đã lưu nhu cầu nhân sự.");}}}><h2 className="text-xl font-bold">{editing?"Chỉnh sửa nhu cầu":"Tạo nhu cầu mới"}</h2><div className="grid gap-4 sm:grid-cols-2"><Field label="Vị trí / nhu cầu"><input id="requirement-title" required className={fieldClass} value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Kỹ năng (phân cách bằng dấu phẩy)"><input required className={fieldClass} value={skills} onChange={e=>setSkills(e.target.value)} placeholder="Python, React, Giao tiếp"/></Field></div><Field label="Mô tả công việc / mục tiêu"><textarea required className={fieldClass} rows={4} value={description} onChange={e=>setDescription(e.target.value)}/></Field>{editing&&<Field label="Trạng thái"><select className={fieldClass} value={status} onChange={e=>setStatus(e.target.value)}><option value="open">Đang mở</option><option value="closed">Đã đóng</option></select></Field>}<div className="flex gap-3"><Button disabled={action.busy}>Lưu nhu cầu</Button>{editing&&<Button type="button" variant="secondary" onClick={clear}>Hủy chỉnh sửa</Button>}</div></form>}
    {rows.data?.map(row=><section className={`${panelClass} space-y-4`} key={row.id}><div className="flex items-start justify-between gap-3"><div><span className="text-xs font-semibold text-primary">{row.status==="open"?"Đang mở":"Đã đóng"}</span><h2 className="mt-2 text-xl font-bold">{row.title}</h2></div><span className="text-xs text-muted">v{row.version}</span></div><p className="whitespace-pre-wrap text-sm leading-6">{row.description}</p><div className="flex flex-wrap gap-2">{row.requiredSkills.map((skill,index)=><span className="rounded-lg bg-background px-3 py-2 text-xs font-semibold" key={index}>{skill}</span>)}</div>{manage&&<div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>edit(row)}>Chỉnh sửa</Button><Button disabled={action.busy} onClick={async()=>{const result=await action.run<Matches>(`/job-requirements/${row.id}/match`,"POST");if(result)setMatches(previous=>({...previous,[row.id]:result}));}}>AI đối chiếu ứng viên</Button><Button variant="ghost" onClick={()=>setRemoving(row)}>Xóa nhu cầu</Button></div>}{matches[row.id]&&<div className="space-y-3 border-t border-border pt-4"><p className="text-sm leading-6">{matches[row.id].summary}</p>{matches[row.id].matches.map(candidate=><div key={candidate.userId} className="rounded-xl bg-background p-4"><div className="flex justify-between gap-3"><Link className="font-semibold text-primary underline" href={`/nhan-su/${candidate.userId}?companyId=${encodeURIComponent(companyId)}`}>{candidate.name}</Link><span className="font-bold">{candidate.matchScore}%</span></div><p className="mt-1 text-xs text-muted">{candidate.jobTitle}</p><p className="mt-2 text-sm leading-6">{candidate.rationale}</p></div>)}</div>}</section>)}{rows.data?.length===0&&<p className={panelClass}>Chưa có nhu cầu nhân sự.</p>}
    <Dialog.Root open={!!removing} onOpenChange={open=>{if(!open)setRemoving(null);}}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-black/40"/><Dialog.Content className="fixed left-1/2 top-1/2 z-50 w-[min(92vw,460px)] -translate-x-1/2 -translate-y-1/2 rounded-2xl bg-surface p-6 shadow-xl"><Dialog.Title className="text-lg font-bold">Xóa nhu cầu nhân sự?</Dialog.Title><Dialog.Description className="mt-3 text-sm text-muted">Nhu cầu “{removing?.title}” sẽ bị xóa. Bạn có thể đóng nhu cầu nếu muốn giữ lại lịch sử.</Dialog.Description><div className="mt-5 flex gap-3"><Button variant="danger" disabled={action.busy} onClick={async()=>{if(removing){const result=await action.run(`/job-requirements/${removing.id}?expectedVersion=${removing.version}`,"DELETE");if(result)setRemoving(null);}}}>Xóa nhu cầu</Button><Dialog.Close asChild><Button variant="secondary">Giữ lại</Button></Dialog.Close></div></Dialog.Content></Dialog.Portal></Dialog.Root>
  </main>;
}
