// Generated by scripts/build-careermate-registry.mjs.
export const careermateAssets = {
  "step-completed": {
    "id": "step-completed",
    "category": "roadmap",
    "src": "/brand/careermate/v1/roadmap/step-completed.svg",
    "width": 256,
    "height": 160,
    "format": "svg"
  },
  "step-current": {
    "id": "step-current",
    "category": "roadmap",
    "src": "/brand/careermate/v1/roadmap/step-current.svg",
    "width": 256,
    "height": 160,
    "format": "svg"
  },
  "step-upcoming": {
    "id": "step-upcoming",
    "category": "roadmap",
    "src": "/brand/careermate/v1/roadmap/step-upcoming.svg",
    "width": 256,
    "height": 160,
    "format": "svg"
  },
  "step-goal": {
    "id": "step-goal",
    "category": "roadmap",
    "src": "/brand/careermate/v1/roadmap/step-goal.svg",
    "width": 256,
    "height": 160,
    "format": "svg"
  },
  "badge-learning": {
    "id": "badge-learning",
    "category": "badges",
    "src": "/brand/careermate/v1/badges/badge-learning.svg",
    "width": 160,
    "height": 176,
    "format": "svg"
  },
  "badge-feedback": {
    "id": "badge-feedback",
    "category": "badges",
    "src": "/brand/careermate/v1/badges/badge-feedback.svg",
    "width": 160,
    "height": 176,
    "format": "svg"
  },
  "badge-team": {
    "id": "badge-team",
    "category": "badges",
    "src": "/brand/careermate/v1/badges/badge-team.svg",
    "width": 160,
    "height": 176,
    "format": "svg"
  },
  "badge-achievement": {
    "id": "badge-achievement",
    "category": "badges",
    "src": "/brand/careermate/v1/badges/badge-achievement.svg",
    "width": 160,
    "height": 176,
    "format": "svg"
  },
  "spot-learning": {
    "id": "spot-learning",
    "category": "illustrations",
    "src": "/brand/careermate/v1/illustrations/spot-learning.svg",
    "width": 320,
    "height": 240,
    "format": "svg"
  },
  "spot-mindmap": {
    "id": "spot-mindmap",
    "category": "illustrations",
    "src": "/brand/careermate/v1/illustrations/spot-mindmap.svg",
    "width": 320,
    "height": 240,
    "format": "svg"
  },
  "spot-documents": {
    "id": "spot-documents",
    "category": "illustrations",
    "src": "/brand/careermate/v1/illustrations/spot-documents.svg",
    "width": 320,
    "height": 240,
    "format": "svg"
  },
  "mark": {
    "id": "mark",
    "category": "brand",
    "src": "/brand/careermate/v1/brand/mark.svg",
    "width": 64,
    "height": 64,
    "format": "svg"
  },
  "mark-mono": {
    "id": "mark-mono",
    "category": "brand",
    "src": "/brand/careermate/v1/brand/mark-mono.svg",
    "width": 64,
    "height": 64,
    "format": "svg"
  }
} as const;
export type CareerMateAssetName = keyof typeof careermateAssets;
